# Generated by Django 4.1.3 on 2022-11-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discipline', models.CharField(max_length=30)),
                ('OpSys', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=20)),
                ('Practicum_Num', models.IntegerField()),
            ],
        ),
    ]
